### PR TITLE
Siegerfliger Livery

### PR DESCRIPTION
**Pull request by FGDATA**
It includes the appropriate paintkits

@IAHM-COL

### CODE REVIEW

**Comment by JWocky** [comment]
I merged it. IAHM-COL did git break your merge rights?

**Comment by FGDATA** [comment]
seems like :S

**Comment by JWocky** [comment]
I deleted and re-added you as collaborator, I hope that works.

**Comment by JWocky** [comment]
I just had a look at the -8vvip in Siegerflieger livery, it looks great!

**Comment by FGDATA** [comment]
:D

Thanks

http://www.thejabberwocky.net/viewtopic.php?f=8&p=1305#p1305

@IAHM-COL

**Pull request merged**
